name: razorpay_integration_flutter_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # PAYMENT
  razorpay_flutter: ^1.2.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  # UI
  flutter_native_splash: ^1.3.3
  flutter_onboard: ^2.0.0
  fluttertoast: ^8.0.8

flutter_native_splash:
  color: "#00223D"
  image: assets/images/pentaio_logo.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

